version: '3.7'
services:

  dashboard:
    build: 
      context: ./
    container_name: RISS_CEIEGH
    hostname: RISS_CEIEGH
    restart: always
    ports:
      - 8056:8056
    networks:
      - network 
    

      
networks:
  network:
    driver: bridge
